language: ruby
rvm:
  - 2.3.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake test
before script:
  - psql -U postgres -c 'create database myreddit-test'
  - RAILS_ENV=test bundle exec rake db:test:prepare
